tried a few things
but nothing works. I cannot make this  error go away.

error TS2339: Property 'model' does not exist on type 'Readonly<Attributes & { children?: ComponentChildren; ref?: Ref<any> | undefined; }>'.